apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-09-22T05:12:10Z"
  generation: 1
  labels:
    app: rclient
  name: rclient
  namespace: default
  resourceVersion: "11279"
  uid: f2a6b492-fbc5-4a57-a144-37de530fea78
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rclient
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rclient
    spec:
      containers:
      - image: yashdaga81/rclient
        imagePullPolicy: Always
        name: rclient
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-09-22T05:12:10Z"
    lastUpdateTime: "2023-09-22T05:12:16Z"
    message: ReplicaSet "rclient-587986f9fd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-09-22T05:13:11Z"
    lastUpdateTime: "2023-09-22T05:13:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
