version: '3'
services:
  backend:
    image: rserver
    ports:
      - '3001:3001'
    networks:
      - mynetwork

  mymongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
